# Generated by Django 3.1.2 on 2021-01-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210108_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='userID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
