# Generated by Django 3.1.2 on 2021-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shoppingitem_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
