# Generated by Django 3.1.2 on 2021-01-08 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_shoppingitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
